### PR TITLE
Add UI

### PR DESCRIPTION
**Pull request by LangYa466**
Added a simple window written in JavaFX, and I couldn't write the compiled part, so I used ChatGPT

### CODE REVIEW

**Comment by Nel1yMinecraft** [comment]
I changed the Build.gradle because China couldn't download the Gradle image, so I changed it to a global Tencent Cloud image

**Comment by LonelyRyF** [comment]
L

**Comment by MolokyMC** [comment]
L

**Comment by siuank** [comment]
幽默

**Comment by YumeGod** [comment]
幽默

**Comment by VitaminB8964** [comment]
天下无双

**Comment by Fadouse** [comment]
> Added a simple window written in JavaFX, and I couldn't write the compiled part, so I used ChatGPT

# 幽默了老弟

**Comment by radioegor146** [comment]
I'm not planning to add UI to this project as for now, so as a better soluton - you can fork or make the UI as separate application and just use `obfuscator` package in gradle dependencies.

**Pull request closed without merging**
